--sinónimos Nicaragua
CREATE OR REPLACE SYNONYM SIMAC.T_GPERSONALCARDAPPLICATION FOR SUNNELNIP1.T_GPERSONALCARDAPPLICATION;
CREATE OR REPLACE SYNONYM SIMAC.T_GCORPORATECARDAPPLICATION FOR SUNNELNIP1.T_GCORPORATECARDAPPLICATION;