--sinónimos Costa Rica
CREATE OR REPLACE SYNONYM SIMAC.T_GPERSONALCARDAPPLICATION FOR SUNNELCRP4.T_GPERSONALCARDAPPLICATION;
CREATE OR REPLACE SYNONYM SIMAC.T_GCORPORATECARDAPPLICATION FOR SUNNELCRP4.T_GCORPORATECARDAPPLICATION;