--sinónimos Guatemala
CREATE OR REPLACE SYNONYM SIMAC.T_GINITSETUPPARAMETER FOR SUNNELGTP1.T_GINITSETUPPARAMETER;
CREATE OR REPLACE SYNONYM SIMAC.T_GPERSONALCARDAPPLICATION FOR SUNNELGTP1.T_GPERSONALCARDAPPLICATION;
CREATE OR REPLACE SYNONYM SIMAC.T_GPROTECTEDCARDAPPLICATION FOR SUNNELGTP1.T_GPROTECTEDCARDAPPLICATION;
CREATE OR REPLACE SYNONYM SIMAC.T_GCORPORATECARDAPPLICATION FOR SUNNELGTP1.T_GCORPORATECARDAPPLICATION;
CREATE OR REPLACE SYNONYM SIMAC.T_GCREDITLINE FOR SUNNELGTP1.T_GCREDITLINE;
CREATE OR REPLACE SYNONYM SIMAC.T_GCARDACCOUNT FOR SUNNELGTP1.T_GCARDACCOUNT;