--ALTER TABLE SIMAC.ALS_CAMPAIGN_BIENVENIDA
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CAMPAIGN_BIENVENIDA CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_CAMPAIGN_BIENVENIDA
(
  ID_NOTIFICATION        INTEGER                NOT NULL,
  NOTIFICATION_COUNTRY   VARCHAR2(100 BYTE),
  NOTIFICATION_STRING    VARCHAR2(100 BYTE),
  NOTIFICATION_CAMPAIGN  INTEGER                NOT NULL,
  NOTIFICATION_ENABLE    CHAR(1 BYTE),
  TEMPLATE_ID            NUMBER                 NOT NULL
);

--DROP SEQUENCE SIMAC.ALS_CAMPAIN_BIENVENIDA_S;
CREATE SEQUENCE SIMAC.ALS_CAMPAIN_BIENVENIDA_S
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAIGN_BIENVENIDA
  BEFORE INSERT ONALS_CAMPAIGN_BIENVENIDA
  FOR EACH ROW
BEGIN
  SELECT ALS_CAMPAIN_BIENVENIDA_S.nextval
  INTO :new.ID_NOTIFICATION
  FROM dual;
END;
/

--DROP PUBLIC SYNONYM ALS_CAMPAIGN_BIENVENIDA;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN_BIENVENIDA FOR SIMAC.ALS_CAMPAIGN_BIENVENIDA;

--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_BIENVENIDA ADD (
  CONSTRAINT ID_NOTIFICATION_BIENV
  PRIMARY KEY
  (ID_NOTIFICATION) 
  );

--ADD FOREIGN KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_BIENVENIDA ADD (
  CONSTRAINT FK_CAMPAIGN_BIENV 
  FOREIGN KEY (NOTIFICATION_CAMPAIGN) 
  REFERENCES SIMAC.ALS_CAMPAIGN (ID_CAMPAIGN)
  ENABLE VALIDATE,
  CONSTRAINT FK_TMP_EMAIL 
  FOREIGN KEY (TEMPLATE_ID) 
  REFERENCES SIMAC.ALS_CMP_EMAIL_TEMPLATE (TEMPLATE_ID)
  ENABLE VALIDATE);

GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN_BIENVENIDA TO SUNNEL;
GRANT SELECT ON SIMAC.ALS_CAMPAIN_BIENVENIDA_S TO SUNNEL;