--ALTER TABLE SIMAC.ALS_CMP_EMAIL_TEMPLATE
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CMP_EMAIL_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_CMP_EMAIL_TEMPLATE
(
  TEMPLATE_ID    INTEGER,
  TEMPLATE_NAME  VARCHAR2(100 BYTE),
  TEMPLATE_BODY  VARCHAR2(4000 BYTE)
);


--DROP SEQUENCE SIMAC.ALS_CMP_EMAIL_TMP_SEQUENCE;
CREATE SEQUENCE SIMAC.ALS_CMP_EMAIL_TMP_SEQUENCE
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;



--  There is no statement for index SIMAC.SYS_C001927636.
--  The object is created when the parent object is created.

CREATE OR REPLACE TRIGGER SIMAC.ALS_CMP_EMAIL_TMP_TRG BEFORE INSERT ON "SIMAC"."ALS_CMP_EMAIL_TEMPLATE"
  FOR EACH ROW
BEGIN
  SELECT ALS_CMP_EMAIL_TMP_SEQUENCE.nextval
  INTO :new.TEMPLATE_ID
  FROM dual;
END;
/


--DROP PUBLIC SYNONYM ALS_CMP_EMAIL_TEMPLATE;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CMP_EMAIL_TEMPLATE FOR SIMAC.ALS_CMP_EMAIL_TEMPLATE;


--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CMP_EMAIL_TEMPLATE ADD (
  PRIMARY KEY
  (TEMPLATE_ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CMP_EMAIL_TEMPLATE TO SUNNEL;  
GRANT SELECT ON SIMAC.ALS_CMP_EMAIL_TMP_SEQUENCE TO SUNNEL;