--ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFICATION
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CAMPAIGN_NOTIFICATION CASCADE CONSTRAINTS;
CREATE TABLE SIMAC.ALS_CAMPAIGN_NOTIFICATION (
    ID_NOTIFICATION INTEGER NOT NULL,
    NOTIFICATION_COUNTRY VARCHAR2(100 BYTE),
    NOTIFICATION_STRING VARCHAR2(100 BYTE),
    NOTIFICATION_CAMPAIGN INTEGER NOT NULL,
    NOTIFICATION_SEQUENCE NUMBER,
    NOTIFICATION_FREQUENCY CHAR(1 BYTE),
    NOTIFICATION_ENABLE CHAR(1 BYTE),
    TEMPLATE_ID NUMBER NOT NULL
);

--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFICATION
ADD (
        CONSTRAINT ID_NOTIFICATION PRIMARY KEY (ID_NOTIFICATION) 
    );

--ADD FOREIGN KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFICATION
ADD (
        CONSTRAINT FK_CAMPAING FOREIGN KEY (NOTIFICATION_CAMPAIGN) REFERENCES SIMAC.ALS_CAMPAIGN (ID_CAMPAIGN) ENABLE VALIDATE,
        CONSTRAINT FK_NOTIFIC_SEG FOREIGN KEY (TEMPLATE_ID) REFERENCES SIMAC.ALS_CMP_EMAIL_TEMPLATE (TEMPLATE_ID) ENABLE VALIDATE
    );

--DROP SEQUENCE SIMAC.ALS_CAMPAIGN_NOTIFICATION_S;
CREATE SEQUENCE SIMAC.ALS_CAMPAIGN_NOTIFICATION_S
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAIGN_NOTIFICATION BEFORE
INSERT ONALS_CAMPAIGN_NOTIFICATION FOR EACH ROW BEGIN
SELECT ALS_CAMPAIGN_NOTIFICATION_S.nextval INTO :new.ID_NOTIFICATION
FROM dual;
END;
/ 

--DROP PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFICATION;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFICATION FOR SIMAC.ALS_CAMPAIGN_NOTIFICATION;

--GRANTS
GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN_NOTIFICATION TO SUNNEL;
GRANT SELECT ON SIMAC.ALS_CAMPAIGN_NOTIFICATION_S TO SUNNEL;