--ALTER TABLE SIMAC.ALS_CAMPAIGN_DENE_COND
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CAMPAIGN_DENE_COND CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_CAMPAIGN_DENE_COND
(
  ID_NOTIFICATION        INTEGER                NOT NULL,
  NOTIFICATION_COUNTRY   VARCHAR2(100 BYTE),
  NOTIFICATION_STRING    VARCHAR2(100 BYTE),
  NOTIFICATION_CAMPAIGN  INTEGER                NOT NULL,
  NOTIFICATION_SEQUENCE  NUMBER,
  STATUS_INDICATOR       CHAR(1 BYTE),
  NOTIFICATION_ENABLE    CHAR(1 BYTE),
  TEMPLATE_ID            NUMBER                 NOT NULL
);

--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_DENE_COND ADD (
  CONSTRAINT ID_NOTIFICATION_COND_DENE
  PRIMARY KEY
  (ID_NOTIFICATION)
);

--ADD FOREIGN KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_DENE_COND ADD (
  CONSTRAINT FK_CAMPAIGN_DENE_COND 
  FOREIGN KEY (NOTIFICATION_CAMPAIGN) 
  REFERENCES SIMAC.ALS_CAMPAIGN (ID_CAMPAIGN)
  ENABLE VALIDATE,
  CONSTRAINT FK_EMAIL_DENE 
  FOREIGN KEY (TEMPLATE_ID) 
  REFERENCES SIMAC.ALS_CMP_EMAIL_TEMPLATE (TEMPLATE_ID)
  ENABLE VALIDATE);

--DROP SEQUENCE SIMAC.ALS_CAMPAIN_DENE_COND_S;
CREATE SEQUENCE SIMAC.ALS_CAMPAIN_DENE_COND_S
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAIGN_DENE_COND
  BEFORE INSERT ONALS_CAMPAIGN_DENE_COND
  FOR EACH ROW
BEGIN
  SELECT ALS_CAMPAIN_DENE_COND_S.nextval
  INTO :new.ID_NOTIFICATION
  FROM dual;
END;
/

--DROP PUBLIC SYNONYM ALS_CAMPAIGN_DENE_COND;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN_DENE_COND FOR SIMAC.ALS_CAMPAIGN_DENE_COND;

--GRANTS
GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN_DENE_COND TO SUNNEL;
GRANT SELECT ON SIMAC.ALS_CAMPAIN_DENE_COND_S TO SUNNEL;