--ALTER TABLE SIMAC.ALS_DENIED_COND_STG DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_DENIED_COND_STG CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_DENIED_COND_STG
(
  ID_CAMPAIGN       NUMBER,
  ID_SETUP          NUMBER,
  CUSTOMER_NAME     VARCHAR2(100 BYTE),
  REMIT_TO          VARCHAR2(100 BYTE),
  TICKET_NUM        CHAR(20 BYTE),
  PRODUCT_NAME      VARCHAR2(60 BYTE),
  COND_REASON       VARCHAR2(245 BYTE),
  STATUS            VARCHAR2(25 BYTE),
  STAGE             VARCHAR2(25 BYTE),
  NOTIFICATION_ID   NUMBER,
  PROCESS_ID        NUMBER,
  PROCESS_STATUS    VARCHAR2(1 BYTE)            DEFAULT 'P',
  CREATION_DATE     DATE                        DEFAULT sysdate,
  LAST_UPDATE_DATE  DATE                        DEFAULT sysdate
);


CREATE UNIQUE INDEX SIMAC.ALS_DENIED_COND_STG_PK ON SIMAC.ALS_DENIED_COND_STG
(NOTIFICATION_ID);


ALTER TABLE SIMAC.ALS_DENIED_COND_STG ADD (
  CONSTRAINT ALS_DENIED_COND_STG_PK
  PRIMARY KEY
  (NOTIFICATION_ID)
  USING INDEX SIMAC.ALS_DENIED_COND_STG_PK
  ENABLE VALIDATE);
