--DROP TABLE SIMAC.T_CMP_INACTIVITY_MONTHS CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_INACTIVITY_MONTHS
(
  PROCESS_ID             NUMBER(12),
  CUSTOMERID             NUMBER(12),
  DELIVEREDTIME          DATE,
  LAST_PURCHASE_DATE     DATE,
  INACTIVE_COUNT_MONTHS  NUMBER(12),
  ALIASNAME              VARCHAR2(100 BYTE),
  EMAIL                  VARCHAR2(100 BYTE),
  PHONENUMBER            VARCHAR2(30 BYTE),
  PRODUCTID              NUMBER(12),
  PRODUCT_DESC           VARCHAR2(100 BYTE)
);