--ALTER TABLE SIMAC.T_CMP_PARAMS
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.T_CMP_PARAMS CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_PARAMS
(
  ID     VARCHAR2(50 BYTE),
  VALUE  VARCHAR2(1000 BYTE),
  TYPE   VARCHAR2(50 BYTE)
);

--  There is no statement for index SIMAC.SYS_C001925163.
--  The object is created when the parent object is created.

--DROP PUBLIC SYNONYM T_CMP_PARAMS;
CREATE OR REPLACE PUBLIC SYNONYM T_CMP_PARAMS FOR SIMAC.T_CMP_PARAMS;

ALTER TABLE SIMAC.T_CMP_PARAMS ADD (
  PRIMARY KEY
  (ID)
);

--GRANTS
GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.T_CMP_PARAMS TO SUNNEL;
