--DROP TABLE SIMAC.T_CMP_PROCESS CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_PROCESS
(
  PROCESS_ID        NUMBER(12),
  ID_CAMPAIGN       NUMBER(12),
  ID_SETUP          NUMBER(12),
  STATUS            VARCHAR2(20 BYTE),
  EXEC_START_TIME   TIMESTAMP(6),
  EXEC_END_TIME     TIMESTAMP(6),
  ROWCOUNT          NUMBER(12),
  ERRORMSG          VARCHAR2(1000 BYTE),
  CAMPAIGN_TYPE     VARCHAR2(50 BYTE),
  DATA_RANGE_START  TIMESTAMP(6),
  DATA_RANGE_END    TIMESTAMP(6),
  SUNNEL_DATE       DATE,
  DAYS_RANGE        NUMBER(12)
);

