--ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE
(
  ID_NOTIFICATION        INTEGER                NOT NULL,
  NOTIFICATION_COUNTRY   VARCHAR2(100 BYTE),
  NOTIFICATION_STRING    VARCHAR2(100 BYTE),
  NOTIFICATION_CAMPAIGN  INTEGER                NOT NULL,
  NOTIFICATION_SEQUENCE  NUMBER,
  NOTIFICATION_DATE_BUY  NUMBER,
  NOTIFICATION_ENABLE    CHAR(1 BYTE),
  TEMPLATE_ID            NUMBER                 NOT NULL
);

--DROP SEQUENCE SIMAC.ALS_CAMPAIN_NOTIFIC_INAC_ONE;

CREATE SEQUENCE SIMAC.ALS_CAMPAIN_NOTIFIC_INAC_ONE
  START WITH 61
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAING_NOTIFICATION
  BEFORE INSERT ON SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE
  FOR EACH ROW
BEGIN
  SELECT ALS_CAMPAIN_NOTIFIC_INAC_ONE.nextval
  INTO :new.ID_NOTIFICATION
  FROM dual;
END;
/

--DROP PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFIC_INAC_ONE;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFIC_INAC_ONE FOR SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE;

--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE ADD (
  CONSTRAINT PK_CAMPAING_INAC_ONE
  PRIMARY KEY
  (ID_NOTIFICATION)
);

-- ADD FOREIGN KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE ADD (
  CONSTRAINT FK_CAMPAING_INAC_ONE 
  FOREIGN KEY (NOTIFICATION_CAMPAIGN) 
  REFERENCES SIMAC.ALS_CAMPAIGN (ID_CAMPAIGN)
  ENABLE VALIDATE,
  CONSTRAINT FK_NOTIFIC_INAC_ONE 
  FOREIGN KEY (TEMPLATE_ID) 
  REFERENCES SIMAC.ALS_CMP_EMAIL_TEMPLATE (TEMPLATE_ID)
  ENABLE VALIDATE);


GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_ONE TO SUNNEL;
