--ALTER TABLE SIMAC.ALS_CAMPAIGN
--DROP PRIMARY KEY CASCADE;
--DROP TABLE SIMAC.ALS_CAMPAIGN CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.ALS_CAMPAIGN
(
  ID_CAMPAIGN              INTEGER              NOT NULL,
  CAMPAIGN_NAME            VARCHAR2(100 BYTE),
  CAMPAIGN_SEND_NAME       VARCHAR2(100 BYTE),
  CAMPAIGN_EMAIL_NAME      VARCHAR2(100 BYTE),
  CAMPAIGN_TEMPLATE_LABEL  VARCHAR2(100 BYTE),
  CAMPAIGN_SMS             VARCHAR2(160 BYTE),
  CAMPAIGN_TYPE            VARCHAR2(50 BYTE),
  CAMPAIGN_SUBJECT         VARCHAR2(100 BYTE)
);

--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN ADD (
  CONSTRAINT ID_CAMPAIN
  PRIMARY KEY
  (ID_CAMPAIGN)
);

--DROP SEQUENCE SIMAC.ALS_CAMPAIGN_SEQUENCE;
CREATE SEQUENCE SIMAC.ALS_CAMPAIGN_SEQUENCE
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAIGN_TRG BEFORE INSERT ON "SIMAC"."ALS_CAMPAIGN"
  FOR EACH ROW
BEGIN
  SELECT ALS_CAMPAIGN_SEQUENCE.nextval
  INTO :new.ID_CAMPAIGN
  FROM dual;
END;
/

--DROP PUBLIC SYNONYM ALS_CAMPAIGN;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN FOR SIMAC.ALS_CAMPAIGN;

--GRANTS
GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN TO SUNNEL;
GRANT SELECT ON SIMAC.ALS_CAMPAIGN_SEQUENCE TO SUNNEL;