--CREATE TABLE
CREATE TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO (
    ID_NOTIFICATION INTEGER NOT NULL,
    NOTIFICATION_COUNTRY VARCHAR2(100 BYTE),
    NOTIFICATION_STRING VARCHAR2(100 BYTE),
    NOTIFICATION_CAMPAIGN INTEGER NOT NULL,
    NOTIFICATION_SEQUENCE NUMBER,
    NOTIFICATION_LAST_BUY NUMBER,
    NOTIFICATION_ENABLE CHAR(1 BYTE),
    TEMPLATE_ID NUMBER NOT NULL
);

--DROP SEQUENCE SIMAC.ALS_CAMPAIN_NOTIFIC_INAC_TWO;
CREATE SEQUENCE SIMAC.ALS_CAMPAIN_NOTIFIC_INAC_TWO
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;



--ADD PRIMARY KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO
ADD (
        CONSTRAINT PK_CAMPAING_INAC_TWO PRIMARY KEY (ID_NOTIFICATION)
    );

--ADD FOREIGN KEY
ALTER TABLE SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO
ADD (
        CONSTRAINT FK_CAMPAING_INAC_TWO FOREIGN KEY (NOTIFICATION_CAMPAIGN) REFERENCES SIMAC.ALS_CAMPAIGN (ID_CAMPAIGN) ENABLE VALIDATE,
        CONSTRAINT FK_NOTIFIC_INAC_TWO FOREIGN KEY (TEMPLATE_ID) REFERENCES SIMAC.ALS_CMP_EMAIL_TEMPLATE (TEMPLATE_ID) ENABLE VALIDATE
    );


--CREATE TRIGGER
CREATE OR REPLACE TRIGGER SIMAC.ALS_CAMPAING_NOTIFICATION_TWO BEFORE
INSERT ON SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO FOR EACH ROW BEGIN
SELECT ALS_CAMPAIN_NOTIFIC_INAC_TWO.nextval INTO :new.ID_NOTIFICATION
FROM dual;
END;
/ 

--DROP PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFIC_INAC_TWO;
CREATE OR REPLACE PUBLIC SYNONYM ALS_CAMPAIGN_NOTIFIC_INAC_TWO FOR SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO;


--GRANTS
GRANT DELETE, INSERT, SELECT, UPDATE ON SIMAC.ALS_CAMPAIGN_NOTIFIC_INAC_TWO TO SUNNEL;
GRANT SELECT ON SIMAC.ALS_CAMPAIN_NOTIFIC_INAC_TWO TO SUNNEL;
