SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  SELECT 
--     ROWID, ID, VALUE, TYPE
--  FROM SIMAC.T_CMP_PARAMS;
--
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('CUST_REQ_TYPES', '3,25,70,84,89,92,98,96,90,53,68,78,91,44,97,95', 'LIST');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('CREDIT_PRODUCT_IDS', '10001,10002,10003,10020', 'LIST');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_INACTIVITY_INITIAL', '332', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_INACTIVITY_MONTHS', '400', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_CARD_DENIED_COND', '332', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_BIENVENIDA', '0', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_CARD_NOT_DELIVERED', '0', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('DAYS_RANGE_REQUIREMENT', '0', 'NUMBER');
Insert into SIMAC.T_CMP_PARAMS
   (ID, VALUE, TYPE)
 Values
   ('PURCHASE_OP_TYPES', '10101,10104', 'LIST');
COMMIT;
