create or replace synonym T_GCARDEMAILADDRESS for SUNNELGTP1.T_GCARDEMAILADDRESS;

create or replace synonym T_GEMAILADDRESS for SUNNELGTP1.T_GEMAILADDRESS;

create or replace synonym T_GBUILDINGADDRESS for SUNNELGTP1.T_GBUILDINGADDRESS;

create or replace synonym T_GBUILDINGADDRESSPHONE for SUNNELGTP1.T_GBUILDINGADDRESSPHONE;

create or replace synonym T_GPHONE for SUNNELGTP1.T_GPHONE;

create or replace synonym T_GPRODUCT for SUNNELGTP1.T_GPRODUCT;

create or replace synonym T_GCUSTOMER for SUNNELGTP1.T_GCUSTOMER;

create or replace synonym T_GCARD for SUNNELGTP1.T_GCARD;

create or replace synonym T_GCUSTOMERREQUIREMENTCARD for SUNNELGTP1.T_GCUSTOMERREQUIREMENTCARD;

create or replace synonym T_GCUSTOMERREQUIREMENTTYPE for SUNNELGTP1.T_GCUSTOMERREQUIREMENTTYPE;

create or replace synonym T_GCUSTOMERREQUIREMENT for SUNNELGTP1.T_GCUSTOMERREQUIREMENT;

create or replace synonym T_GCUSTOMERREQUIREMENTACCOUNT for SUNNELGTP1.T_GCUSTOMERREQUIREMENTACCOUNT;

create or replace synonym T_GCUSTOMERREQUIREMENTCUSTOMER for SUNNELGTP1.T_GCUSTOMERREQUIREMENTCUSTOMER;

create or replace synonym T_GAPPLICATION for SUNNELGTP1.T_GAPPLICATION;

create or replace synonym T_GDEBITOPERATION for SUNNELGTP1.T_GDEBITOPERATION;

