DROP TABLE SIMAC.T_CMP_INACTIVITY_INITIAL CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_INACTIVITY_INITIAL
(
  PROCESS_ID           NUMBER(12),
  CUSTOMERID           NUMBER(12),
  DELIVEREDTIME        DATE,
  INACTIVE_COUNT_DAYS  NUMBER(12),
  ALIASNAME            VARCHAR2(100 BYTE),
  EMAIL                VARCHAR2(100 BYTE),
  PHONENUMBER          VARCHAR2(30 BYTE),
  PRODUCTID            NUMBER(12),
  PRODUCT_DESC         VARCHAR2(100 BYTE)
);
