--DROP TABLE SIMAC.T_CMP_CARD_NOT_DELIVERED CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_CARD_NOT_DELIVERED
(
  PROCESS_ID                NUMBER(12),
  APPLICATIONID             NUMBER(12),
  AUTHORIZATIONDATE         DATE,
  AUTHORIZATION_COUNT_DAYS  NUMBER(12),
  CUSTOMERID                NUMBER(12),
  ALIASNAME                 VARCHAR2(100 BYTE),
  EMAIL                     VARCHAR2(100 BYTE),
  PHONENUMBER               VARCHAR2(30 BYTE),
  PRODUCTID                 NUMBER(12),
  PRODUCT_DESC              VARCHAR2(100 BYTE)
);