--DROP TABLE SIMAC.T_CMP_BIENVENIDA CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_BIENVENIDA
(
  PROCESS_ID     NUMBER(12),
  CUSTOMERID     NUMBER(12),
  DELIVEREDTIME  DATE,
  ALIASNAME      VARCHAR2(100 BYTE),
  EMAIL          VARCHAR2(100 BYTE),
  PHONENUMBER    VARCHAR2(30 BYTE),
  PRODUCTID      NUMBER(12),
  PRODUCT_DESC   VARCHAR2(100 BYTE)
);
