--DROP TABLE SIMAC.T_CMP_REQUIREMENT CASCADE CONSTRAINTS;

CREATE TABLE SIMAC.T_CMP_REQUIREMENT
(
  PROCESS_ID                    NUMBER(12),
  CUSTOMERREQUIREMENTID         NUMBER(12),
  CUSTOMERREQUIREMENTTYPEID     NUMBER(12),
  CUSTOMERREQUIREMENTTYPE_DESC  VARCHAR2(100 BYTE),
  STATUS                        VARCHAR2(20 BYTE),
  STAGE                         VARCHAR2(20 BYTE),
  CUSTOMERID                    NUMBER(12),
  ALIASNAME                     VARCHAR2(100 BYTE),
  EMAIL                         VARCHAR2(100 BYTE),
  PHONENUMBER                   VARCHAR2(30 BYTE),
  PRODUCTID                     NUMBER(12),
  PRODUCT_DESC                  VARCHAR2(100 BYTE)
);